// <auto-generated />
using System;
using Com.MicroMarketConnect.API.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Com.MicroMarketConnect.API.Infrastructure.Migrations
{
    [DbContext(typeof(MicroMarketConnectDbContext))]
    partial class MicroMarketConnectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mmc")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Organizations.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations", "mmc");
                });

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Organizations.OrganizationMemberEntity", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Member");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationMembers", "mmc");
                });

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Roles.RoleEntity", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("PlatformUser");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Name");

                    b.ToTable("Roles", "mmc");

                    b.HasData(
                        new
                        {
                            Name = "PlatformUser",
                            Description = "Simple access to application.",
                            DisplayName = "Platform user"
                        },
                        new
                        {
                            Name = "PlatformModerator",
                            Description = "Moderating users and organizations behaviors on the platform.",
                            DisplayName = "Platform moderator"
                        },
                        new
                        {
                            Name = "PlatformAdmin",
                            Description = "Managing the platform.",
                            DisplayName = "Platform administrator"
                        });
                });

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "mmc");
                });

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Users.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId", "RoleName");

                    b.HasIndex("RoleName");

                    b.ToTable("UserRoles", "mmc");
                });

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Organizations.OrganizationMemberEntity", b =>
                {
                    b.HasOne("Com.MicroMarketConnect.API.Infrastructure.Identity.Organizations.OrganizationEntity", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Com.MicroMarketConnect.API.Infrastructure.Identity.Users.UserEntity", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Users.UserRoleEntity", b =>
                {
                    b.HasOne("Com.MicroMarketConnect.API.Infrastructure.Identity.Roles.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Com.MicroMarketConnect.API.Infrastructure.Identity.Users.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Organizations.OrganizationEntity", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Roles.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Com.MicroMarketConnect.API.Infrastructure.Identity.Users.UserEntity", b =>
                {
                    b.Navigation("OrganizationMemberships");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
